### ISSUE TITLE
Failure to download file

### ISSUE THREAD

**Issue by jzneter1** [xorus/telegram-image-downloader#1]
C:\Telegram>node index
https://api.telegram.org/file/*****************************************************/photos/file_0.jpg
events.js:183
      throw er; // Unhandled 'error' event

Error: ENOENT: no such file or directory, open 'c:\Telegram\    elegram
ieuwe map\302140707277844.jpg'

The map i made to direct my download to is "c:\telegram\nieuwe map"

**Comment by xorus** [comment]
Oups ! I'm sorry I didn't get a notification of your issue ! Did you manage to find the problem / does it still happen / do you still need help ? 
Yes, I know I'm late by... A YEAR
